### ISSUE TITLE
execute-git.sh script not working on macOS

### ISSUE THREAD

**Issue by kastork** [rcw3bb/simple-git#1]
I've just started experimenting with this plugin.  It looks promising for my project, thank you for releasing it.

On a mac, the script file `execute-git.sh` that is populated by the plugin and then called by it  has a couple problems.

1. the execute bit is not set, so it won't execute
2. after fixing that, the script still doesn't work because the line endings are CRLF instead of LF.  (so you get, for example

```bash
› ./build/simple/git/scripts/execute-git.sh 
env: bash\r: No such file or directory
```

Consequently, the `GitPull` task (and probably some others) fail with less than useful error messages.

After fixing both, things seem to work.

**Comment by rcw3bb** [comment]
Hi @kastork, I've never tested it with macOS yet. 

The error messages must be coming from the git executable. Maybe in your gitTask you can add the **--verbose** flag. So that git can spit out more information.

If you want to see what is the actual command being executed. You can set the following on your build script:

simple_git.verbose = true

Tell me it this one helps.

**Comment by rcw3bb** [comment]
Hi @kastork, can you try version 1.3.0 for your issue.

**Comment by kastork** [comment]
I've tried it.  Seems to work well in both Windows and Mac now.
Thanks!

**Comment by rcw3bb** [comment]
Hi @kastork, nice to that. I'm closing this issue now.
